package com.gui.working;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.database.*;
import com.gui.log.Loading;

import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Cary60_1
 */
public class DataEntry extends javax.swing.JFrame implements Runnable {
    private int hour,minutes,seconds;
    private Thread t;
    Date date;
    ManageDataEntryDB manageDataEntryDB;
    LocalDateTime currentTime;
    ManageAccount manageAccount;
    List<Account> account;
    /**
     * Creates new form DataComplete
     */
    public DataEntry() {
        super("Introducerea datelor");
        setResizable(false);
        initComponents();
        currentTime = LocalDateTime.now();
        currentDate();
        t= new Thread(this);
        t.start();
        manageAccount = new ManageAccount();
        account= manageAccount.listUsers(Loading.username);
        aleteleJField.setVisible(false);
        manageDataEntryDB= new ManageDataEntryDB();
        showFiles(Loading.username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        clientNamejComboBox = new javax.swing.JComboBox();
        raporNumbertSniper = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sigiliuNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        intialDate = new com.toedter.calendar.JDateChooser();
        dateOfRaportDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        finalDate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        sampleNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        aleteleJField = new javax.swing.JTextField();
        dateOfGetSample = new com.toedter.calendar.JDateChooser();
        aleteleJField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        conclusionData = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        documentsArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        inspectorName = new javax.swing.JComboBox();
        degree = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        speciality = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        agesOfWork = new javax.swing.JSpinner();
        backBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        eraseBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        backMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        closeMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        deleteMenuItem = new javax.swing.JMenuItem();
        updateMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        dateTxt = new javax.swing.JMenu();
        timeTxt = new javax.swing.JMenu();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "Raport de încercări", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(0, 102, 204))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText(" din");

        clientNamejComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clientNamejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Biroul Vamal Centru", "Biroul Vamal Sud", "Biroul Vamal Nord", "Direcţia Investigare Fraude Vamale", "Direcţia Urmărire Penală", "Altele" }));
        clientNamejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientNamejComboBoxActionPerformed(evt);
            }
        });

        raporNumbertSniper.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("2. Adresa clientului (organului vamal):");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("1. Numele clientului (organului vamal):");

        sigiliuNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("5. Data primirii obiectului de încercări în laborator:");

        intialDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dateOfRaportDateChooser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("3. Codul probei: ");

        finalDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("7. Proba a fost însoțită de următoarele documente:");

        sampleNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("6. Data începerii/finisării încercărilor: ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("/");

        aleteleJField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dateOfGetSample.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        aleteleJField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nr. ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("4. Nr. sigiliu: ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("8. Concluzie:");

        conclusionData.setColumns(20);
        conclusionData.setRows(5);
        jScrollPane2.setViewportView(conclusionData);

        documentsArea.setColumns(20);
        documentsArea.setRows(5);
        jScrollPane3.setViewportView(documentsArea);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("9. Întocmit: ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Nume, prenume");

        inspectorName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inspectorName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mihail SECU", "Radu STAFI", "Igor GRIBINIUC", "Stela BODRUG", "Vasile BENEA", "Victor NICHIFOR", "Eugeniu SPIVACENCO" }));
        inspectorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inspectorNameActionPerformed(evt);
            }
        });

        degree.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        degree.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inspector principal, SCM", "Inspector superior, SCM", "Inspector, SCM" }));
        degree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Funcţia");

        speciality.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        speciality.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Superioare/Chimie", "Superioare/Fizică", "Superioare/Metrologie", "Superioare/Merceologie", "Superioare/Economie", "Superioare/Tehnologie" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Studii/ Specialitate ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Vechimea");

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        backBtn.setText("La Meniul Principal");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_mic.png"))); // NOI18N
        saveBtn.setText("Salvează");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        eraseBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eraseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file.png"))); // NOI18N
        eraseBtn.setText("Șterge");
        eraseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(raporNumbertSniper, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(dateOfRaportDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(inspectorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(degree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(speciality, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel13)
                                                                .addGap(110, 110, 110)
                                                                .addComponent(jLabel14)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel15)
                                                                .addGap(39, 39, 39)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel16)
                                                        .addComponent(agesOfWork, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(14, 14, 14))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dateOfGetSample, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel8))
                                                .addGap(147, 147, 147)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(sampleNumber)
                                                        .addComponent(sigiliuNumber)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(22, 22, 22)
                                                .addComponent(aleteleJField2))
                                        .addComponent(jScrollPane3)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel1))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(intialDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(finalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(aleteleJField)
                                                        .addComponent(clientNamejComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(backBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(71, 71, 71)
                                                .addComponent(eraseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(raporNumbertSniper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3))
                                        .addComponent(dateOfRaportDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(clientNamejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aleteleJField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(aleteleJField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(sampleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(sigiliuNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(dateOfGetSample, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(intialDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)
                                        .addComponent(finalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(inspectorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(degree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(speciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(agesOfWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(saveBtn)
                                        .addComponent(eraseBtn))
                                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(36, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(25, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jMenu1.setForeground(new java.awt.Color(153, 0, 153));
        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu1.add(jSeparator1);

        backMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        backMenuItem.setText("Înapoi la Meniul Principal");
        backMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(backMenuItem);
        jMenu1.add(jSeparator3);

        closeMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        closeMenuItem.setText("Close");
        closeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(closeMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(153, 0, 153));
        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        deleteMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file.png"))); // NOI18N
        deleteMenuItem.setText("Şterge ");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(deleteMenuItem);

        updateMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_mic.png"))); // NOI18N
        updateMenuItem.setText("Slvează");
        updateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(updateMenuItem);
        jMenu2.add(jSeparator2);

        jMenuBar1.add(jMenu2);

        dateTxt.setForeground(new java.awt.Color(153, 0, 153));
        dateTxt.setText("Data");
        dateTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(dateTxt);

        timeTxt.setForeground(new java.awt.Color(153, 0, 153));
        timeTxt.setText("Timpul");
        timeTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(timeTxt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void backMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        Home home = new Home();
        home.setVisible(true);
    }

    private void closeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void updateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void clientNamejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(clientNamejComboBox.getSelectedItem().toString().equals("Altele")){
            aleteleJField.setVisible(true);
            aleteleJField2.setText("");
            revalidate();
            repaint();
        }else{
            aleteleJField.setVisible(false);
            revalidate();
            repaint();
            String data = (String) clientNamejComboBox.getSelectedItem();

            switch(data){
                case "Biroul Vamal Centru": aleteleJField2.setText("mun. Chişinău, bd. Dacia 49/6");  break;
                case "Biroul Vamal Sud": aleteleJField2.setText("or. Cahul, şos. Prieteniei 1"); break;
                case "Biroul Vamal Nord": aleteleJField2.setText("or. Bălţi str. Cicicalo 1"); break;
                default: aleteleJField2.setText("mun. Chișinău, str. Nicolae Starostenco, 30"); break;
            }
        }
    }

    private void inspectorNameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void degreeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        Home home = new Home();
        home.setVisible(true);
    }

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        List<DataEntryDB> list = manageDataEntryDB.listOfFiles(Loading.username);
        if(dateOfRaportDateChooser.getDate()==null ||  aleteleJField2.getText().isEmpty() || sampleNumber.getText().isEmpty() || sigiliuNumber.getText().isEmpty() || dateOfGetSample.getDate()==null || intialDate.getDate()==null || finalDate.getDate()==null ||  documentsArea.getText().isEmpty() || conclusionData.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Completaţi toate câmpurile.",
                    "Lipsesc Date", JOptionPane.WARNING_MESSAGE);
        }else {
            if (list.size() > 0) {
                manageDataEntryDB.updateData(list.get(0).getDataEntryId(), (int) raporNumbertSniper.getValue(), dateOfRaportDateChooser.getDate(), clientNamejComboBox.getSelectedItem().toString(), aleteleJField2.getText(), sampleNumber.getText(), sigiliuNumber.getText(), dateOfGetSample.getDate(), intialDate.getDate(), finalDate.getDate(), documentsArea.getText(), conclusionData.getText(), inspectorName.getSelectedItem().toString(), degree.getSelectedItem().toString(), speciality.getSelectedItem().toString(), (int) agesOfWork.getValue());

            } else {
                manageDataEntryDB.addNewFile((int) raporNumbertSniper.getValue(), dateOfRaportDateChooser.getDate(), clientNamejComboBox.getSelectedItem().toString(), aleteleJField2.getText(), sampleNumber.getText(), sigiliuNumber.getText(), dateOfGetSample.getDate(), intialDate.getDate(), finalDate.getDate(), documentsArea.getText(), conclusionData.getText(), inspectorName.getSelectedItem().toString(), degree.getSelectedItem().toString(), speciality.getSelectedItem().toString(), (int) agesOfWork.getValue(), account.get(0));
            }
            JOptionPane.showMessageDialog(null, "Datele au fost inserate cu succes în Baza de Date");
        }

    }

    private void eraseBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        List<DataEntryDB> list = manageDataEntryDB.listOfFiles(Loading.username);
        if (list.size() > 0) {
            Object[] options = {"Da", "Nu"};
            int n = JOptionPane.showOptionDialog(this,
                    "Doriţi să ştergeţi toate datele ?",
                    "Întrebare",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[1]);
            if (n == 0) {
                manageDataEntryDB.deleteData(list.get(0).getDataEntryId());
            }
        }
        JOptionPane.showMessageDialog(null, "Datele au fost șterse cu succes");
        showFiles(Loading.username);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                //if ("Nimbus".equals(info.getName())) {
                //  javax.swing.UIManager.setLookAndFeel(info.getClassName());
                //break;
                // }
                UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JSpinner agesOfWork;
    private javax.swing.JTextField aleteleJField;
    private javax.swing.JTextField aleteleJField2;
    private javax.swing.JButton backBtn;
    private javax.swing.JMenuItem backMenuItem;
    private javax.swing.JComboBox clientNamejComboBox;
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JTextArea conclusionData;
    private com.toedter.calendar.JDateChooser dateOfGetSample;
    private com.toedter.calendar.JDateChooser dateOfRaportDateChooser;
    private javax.swing.JMenu dateTxt;
    private javax.swing.JComboBox degree;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JTextArea documentsArea;
    private javax.swing.JButton eraseBtn;
    private com.toedter.calendar.JDateChooser finalDate;
    private javax.swing.JComboBox inspectorName;
    private com.toedter.calendar.JDateChooser intialDate;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSpinner raporNumbertSniper;
    private javax.swing.JTextField sampleNumber;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField sigiliuNumber;
    private javax.swing.JComboBox speciality;
    private javax.swing.JMenu timeTxt;
    private javax.swing.JMenuItem updateMenuItem;
    // End of variables declaration

    @Override
    public void run() {
        while(true){
            try {
                Calendar cal = new GregorianCalendar();
                seconds = cal.get(Calendar.SECOND);
                minutes =  cal.get(Calendar.MINUTE);
                hour = cal.get(Calendar.HOUR);

                SimpleDateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
                Date date = cal.getTime();
                String time= dateFormat.format(date);
                timeTxt.setText(" Ora: "+time);
                t.sleep(10);
            } catch (InterruptedException ex) {
                Logger.getLogger(DataEntry.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void currentDate(){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year =  cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        dateTxt.setText(String.format("Data : %02d/%02d/%04d",day,(month+1),year));


    }

    public void showFiles(String username){
        List<DataEntryDB> list = manageDataEntryDB.listOfFiles(username);
        if(list.size()>0){
            raporNumbertSniper.setValue(list.get(0).getReportNumber());
            dateOfRaportDateChooser.setDate(list.get(0).getReportDate());
            clientNamejComboBox.setSelectedItem(list.get(0).getClientName());
            aleteleJField2.setText(list.get(0).getClientAdrress());
            sampleNumber.setText(list.get(0).getSampleCode());
            sigiliuNumber.setText(list.get(0).getSealNumber());
            dateOfGetSample.setDate(list.get(0).getGetSample());
            intialDate.setDate(list.get(0).getItialDate());
            finalDate.setDate(list.get(0).getFinalDate());
            documentsArea.setText(list.get(0).getDocuments());
            conclusionData.setText(list.get(0).getConclusion());
            inspectorName.setSelectedItem(list.get(0).getInspectorName());
            degree.setSelectedItem(list.get(0).getDegree());
            speciality.setSelectedItem(list.get(0).getSpeciality());
            agesOfWork.setValue(list.get(0).getAgeOfWork());
        }else{
            raporNumbertSniper.setValue(0);
            date = Date.from(currentTime.atZone(ZoneId.systemDefault()).toInstant());
            dateOfRaportDateChooser.setDate(date);
            clientNamejComboBox.setSelectedItem("");
            aleteleJField2.setText("");
            sampleNumber.setText("");
            sigiliuNumber.setText("");
            dateOfGetSample.setDate(null);
            intialDate.setDate(null);
            finalDate.setDate(null);
            documentsArea.setText("");
            conclusionData.setText("");
            inspectorName.setSelectedItem("");
            degree.setSelectedItem("");
            speciality.setSelectedItem("");
            agesOfWork.setValue(0);
        }


    }

}
