package com.gui.working;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.backend.OpenFile;
import com.backend.PrintData;
import com.database.*;
import com.gui.log.Loading;
import com.gui.log.LogIn;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.ParseException;
import java.text.SimpleDateFormat;


/**
 *
 * @author Cary60_1
 */
public class Home extends javax.swing.JFrame implements Runnable{
    private int hour,minutes,seconds;
    private Thread t=null;
    ManageAccountSavePath manageAccountSavePath;
    ManageAccount manageAccount;
    List<Account> account;
    ManageImage manageImage;
    ManageEdxrfDB manageEdxrfDB;
    ManageDataEntryDB manageDataEntryDB;
    List<EdxrfDB> edxrfs;
    List<Image> images;
    List<DataEntryDB> dataEntries;
    List<AccountSavePath> accountSavePaths;
    OpenFile openFile;
    PrintData printData;
    /**
     * Creates new form Home
     */
    public Home() {
        super("Meniul Principal");
        setResizable(false);
        initComponents();
        currentDate();
        showUser();
        t= new Thread(this);
        t.start();
        manageAccount = new ManageAccount();
        account= manageAccount.listUsers(Loading.username);
        manageAccountSavePath=new ManageAccountSavePath();
    }

    public void showUser(){
        String name = userLlb.getText();
        name+= Loading.username;
        userLlb.setText(name);
    }

    public void currentDate(){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year =  cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        dateTxt.setText(String.format("Data : %02d/%02d/%04d",day,(month+1),year));

      /*  int seconds = cal.get(Calendar.SECOND);
        int minutes =  cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);

        timeTxt.setText(String.format("   Ora: %02d:%02d:%02d",hour,minutes,seconds));*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        welcomeLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fotoBtn = new javax.swing.JButton();
        edxrfBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dataBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        reportBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        aboutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userLlb = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        savejMenuItem = new javax.swing.JMenuItem();
        generateReportjMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        aboutjMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        LogOutItemMenu = new javax.swing.JMenuItem();
        dateTxt = new javax.swing.JMenu();
        timeTxt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(153, 0, 153));
        welcomeLbl.setText("#Bine aţi venit utilizator");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 1, true), "Proiectare", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        fotoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photo.png"))); // NOI18N
        fotoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotoBtnActionPerformed(evt);
            }
        });

        edxrfBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder.png"))); // NOI18N
        edxrfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edxrfBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Încărcarea Fişierele Foto");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("Completarea Datelor");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Încărcarea Fişierele EDXRF");

        dataBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/survey.png"))); // NOI18N
        dataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(edxrfBtn)
                                        .addComponent(jLabel2))
                                .addGap(179, 179, 179)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(fotoBtn))
                                .addGap(0, 21, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(160, 160, 160)
                                                .addComponent(dataBtn)
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fotoBtn)
                                        .addComponent(dataBtn)
                                        .addComponent(edxrfBtn))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 1, true), "Executare", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(0, 51, 153))); // NOI18N

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        reportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Generate-tables-icon.png"))); // NOI18N
        reportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 153));
        jLabel5.setText("Salvarea Fişierului Word");

        aboutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/About.png"))); // NOI18N
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Generarea Raportului");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("Despre ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(saveBtn)
                                        .addComponent(jLabel5))
                                .addGap(176, 176, 176)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(reportBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(aboutBtn)
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(57, 57, 57))))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(saveBtn)
                                        .addComponent(reportBtn)
                                        .addComponent(aboutBtn))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel7))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/63056d7b-9b08-4717-940a-d9bbef1308ef_200x200.png"))); // NOI18N

        userLlb.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        userLlb.setForeground(new java.awt.Color(153, 0, 153));
        userLlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLlb.setText("#");

        jMenu1.setForeground(new java.awt.Color(153, 0, 153));
        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        savejMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        savejMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_mic.png"))); // NOI18N
        savejMenuItem.setText("Salvare Fişier");
        savejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(savejMenuItem);

        generateReportjMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        generateReportjMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Generate-tables-icon_mic.png"))); // NOI18N
        generateReportjMenuItem.setText("Generare Raport");
        generateReportjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportjMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(generateReportjMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(153, 0, 153));
        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        aboutjMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AboutMic.png"))); // NOI18N
        aboutjMenuItem.setText("Despre");
        jMenu2.add(aboutjMenuItem);
        jMenu2.add(jSeparator1);

        LogOutItemMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signin.png"))); // NOI18N
        LogOutItemMenu.setText("Delogare");
        LogOutItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutItemMenuActionPerformed(evt);
            }
        });
        jMenu2.add(LogOutItemMenu);

        jMenuBar1.add(jMenu2);

        dateTxt.setForeground(new java.awt.Color(153, 0, 153));
        dateTxt.setText("Data");
        dateTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(dateTxt);

        timeTxt.setForeground(new java.awt.Color(153, 0, 153));
        timeTxt.setText("Timpul");
        timeTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(timeTxt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(174, 174, 174)
                                                                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(163, 163, 163)
                                                                .addComponent(userLlb, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(userLlb))
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void fotoBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        Images images = new Images();
        images.setVisible(true);
    }

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        List<AccountSavePath> list = manageAccountSavePath.listOfPath(Loading.username);
        JFileChooser fileChooser = new JFileChooser();
        int retval = fileChooser.showSaveDialog(saveBtn);
        if (retval == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            if (file == null) {
                return;
            }
            if (!file.getName().toLowerCase().endsWith(".docx")) {
                file = new File(file.getParentFile(), file.getName() + ".docx");
            }
            if(list.size()>0) {
                manageAccountSavePath.updatePath(list.get(0).getPathSaveId(),file.getAbsolutePath());
            }else {
                manageAccountSavePath.addNewAccountSavePath(file.getAbsolutePath(),account.get(0));
            }

        }else{
            JOptionPane.showMessageDialog(null,"Nu ați salavat nici un fișier");
        }


    }

    private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        ProgressBaru progressBaru = new ProgressBaru();
        progressBaru.setVisible(true);
        progressBaru.setUploading();
    }

    public int doSomething()
    {
        manageImage = new ManageImage();
        manageEdxrfDB = new ManageEdxrfDB();
        manageDataEntryDB = new ManageDataEntryDB();
        edxrfs = manageEdxrfDB.listOfFiles(Loading.username);
        images = manageImage.listOfImages(Loading.username);
        dataEntries = manageDataEntryDB.listOfFiles(Loading.username);
        accountSavePaths = manageAccountSavePath.listOfPath(Loading.username);
        if(edxrfs.size()>0 && images.size()>0 && dataEntries.size()>0 && accountSavePaths.size()>0){
            String [] str = new String[edxrfs.size()];
            for(int i=0;i<edxrfs.size();i++){
                str[i]=edxrfs.get(i).getPath();
            }
            for(int i=0;i<edxrfs.size();i++){
                System.out.println(str[i]);
            }
            File [] file = new File[edxrfs.size()];
            for(int i=0;i<edxrfs.size();i++){
                file[i]= new File(str[i]);
            }
            openFile = new OpenFile(file);
            printData = new PrintData(accountSavePaths.get(0).getPath());
            try {

                SimpleDateFormat formatter = new SimpleDateFormat("dd.MM.yyyy");
                SimpleDateFormat formatter1 = new SimpleDateFormat("dd MMMM yyyy");
                String dateOfRaport = formatter1.format(dataEntries.get(0).getReportDate());
                String dateOfRaportFooter = formatter.format(dataEntries.get(0).getReportDate());
                String getSample = formatter.format(dataEntries.get(0).getGetSample());
                String initial=  formatter.format(dataEntries.get(0).getItialDate());
                String finals = formatter.format(dataEntries.get(0).getFinalDate());

                String [] data={String.valueOf(dataEntries.get(0).getReportNumber()),dateOfRaport,dateOfRaportFooter,
                        dataEntries.get(0).getClientName(),dataEntries.get(0).getClientAdrress(),dataEntries.get(0).getSampleCode(),
                        dataEntries.get(0).getSealNumber(),getSample, initial,
                        finals,dataEntries.get(0).getDocuments(),dataEntries.get(0).getConclusion(),
                        dataEntries.get(0).getInspectorName(), dataEntries.get(0).getDegree(), dataEntries.get(0).getSpeciality(),
                        String.valueOf(dataEntries.get(0).getAgeOfWork())};
                String [] imageDatasSampleNumber= new String[manageImage.listOfImages(Loading.username).size()];
                String [] imageDescriptiom = new String[manageImage.listOfImages(Loading.username).size()];
                String [] imagePath = new String[manageImage.listOfImages(Loading.username).size()];
                for (int i = 0; i < imageDatasSampleNumber.length; i++) {
                    imageDatasSampleNumber[i] = manageImage.listOfImages(Loading.username).get(i).getSampleNumber();
                    imageDescriptiom[i] = manageImage.listOfImages(Loading.username).get(i).getDescription();
                    imagePath[i] = manageImage.listOfImages(Loading.username).get(i).getPhotoPath();
                }

                printData.showData(data,imageDatasSampleNumber,imageDescriptiom,imagePath);
                OpenWord.open(accountSavePaths.get(0).getPath());


            } catch (Exception e) {
                e.printStackTrace();
            }

        }else{
            JOptionPane.showMessageDialog(null,"Nu ați încărcat toate datele sau nu le-ați completa");
        }

        return 0;
    }

    private void edxrfBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        EDXRF edxrf = new EDXRF();
        edxrf.setVisible(true);
    }

    private void generateReportjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void savejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void dataBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        DataEntry dataEntry = new DataEntry();
        dataEntry.setVisible(true);
    }

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        About about = new About();
        about.setVisible(true);
    }

    private void LogOutItemMenuActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        LogIn logIn = new LogIn();
        logIn.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JMenuItem LogOutItemMenu;
    private javax.swing.JButton aboutBtn;
    private javax.swing.JMenuItem aboutjMenuItem;
    private javax.swing.JButton dataBtn;
    private javax.swing.JMenu dateTxt;
    private javax.swing.JButton edxrfBtn;
    private javax.swing.JButton fotoBtn;
    private javax.swing.JMenuItem generateReportjMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton reportBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JMenuItem savejMenuItem;
    private javax.swing.JMenu timeTxt;
    private javax.swing.JLabel userLlb;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration

    @Override
    public void run() {

        while(true){
            try {
                Calendar cal = new GregorianCalendar();
                seconds = cal.get(Calendar.SECOND);
                minutes =  cal.get(Calendar.MINUTE);
                hour = cal.get(Calendar.HOUR);

                SimpleDateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
                Date date = cal.getTime();
                String time= dateFormat.format(date);
                timeTxt.setText(" Ora: "+time);
                t.sleep(10);
            } catch (InterruptedException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
